version: '3.1'

services:

  db:
      image: mysql:latest
      deploy:
         restart_policy:
           condition: on-failure
           delay: 5s
           max_attempts: 3
           window: 120s
      command: --default-authentication-plugin=mysql_native_password --initialize-insecure=false
      environment:
        MYSQL_DATABASE: inholland
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: mysql
      volumes:
        - ./sql-scripts:/docker-entrypoint-initdb.d/
      networks:
      - php  

  server:
    image: wimmelsoft/php-mysql-pdo:0.1
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 80:80
    networks:
      - php
    volumes:
      - ./src:/var/www/html

  phpmyadmin:
    image: phpmyadmin:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - php

networks:
  php:
    driver: overlay
